export const GETPOKEMON = 'GETPOKEMON'



export const SETFILTER = "SETFILTER"
export const SETSORT = "SETSORT"

export const SETSHOWPOKEMON = 'SETSHOWPOKEMON'
export const GETPOKEFOUND = 'GETPOKEFOUND'